### ISSUE TITLE
Support for  zh-TW ("Chinese (Taiwan)")[TRANSLATABLE]

### ISSUE THREAD

**Issue by doggy8088** [jdepoix/youtube-transcript-api#310]
**Is your feature request related to a problem? Please describe.**

Unable to get `zh-TW` caption.

**Describe the solution you'd like**

I can get it by this:
```py
YouTubeTranscriptApi.get_transcript("jNzlJXQpr3k", ('en', 'zh-TW'))
```

I think it should get the only one caption by default. No matter what language it have.

**Describe alternatives you've considered**

No.

**Additional context**

YouTube Link: https://www.youtube.com/live/jNzlJXQpr3k

Here is the log:

```log
root@eced1610fe6e:/app/youtube-transcript-api# python
Python 3.12.4 (main, Aug  2 2024, 14:41:30) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from youtube_transcript_api import YouTubeTranscriptApi
>>> YouTubeTranscriptApi.get_transcript("jNzlJXQpr3k")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/youtube-transcript-api/youtube_transcript_api/_api.py", line 137, in get_transcript
    return cls.list_transcripts(video_id, proxies, cookies).find_transcript(languages).fetch(preserve_formatting=preserve_formatting)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/youtube-transcript-api/youtube_transcript_api/_transcripts.py", line 183, in find_transcript
    return self._find_transcript(language_codes, [self._manually_created_transcripts, self._generated_transcripts])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/youtube-transcript-api/youtube_transcript_api/_transcripts.py", line 219, in _find_transcript
    raise NoTranscriptFound(
youtube_transcript_api._errors.NoTranscriptFound:
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=jNzlJXQpr3k! This is most likely caused by:

No transcripts were found for any of the requested language codes: ('en',)

For this video (jNzlJXQpr3k) transcripts are available in the following languages:

(MANUALLY CREATED)
 - zh-TW ("Chinese (Taiwan)")[TRANSLATABLE]

(GENERATED)
None

(TRANSLATION LANGUAGES)
 - ab ("Abkhazian")
 - aa ("Afar")
 - af ("Afrikaans")
 - ak ("Akan")
 - sq ("Albanian")
 - am ("Amharic")
 - ar ("Arabic")
 - hy ("Armenian")
 - as ("Assamese")
 - ay ("Aymara")
 - az ("Azerbaijani")
 - bn ("Bangla")
 - ba ("Bashkir")
 - eu ("Basque")
 - be ("Belarusian")
 - bho ("Bhojpuri")
 - bs ("Bosnian")
 - br ("Breton")
 - bg ("Bulgarian")
 - my ("Burmese")
 - ca ("Catalan")
 - ceb ("Cebuano")
 - zh-Hans ("Chinese (Simplified)")
 - zh-Hant ("Chinese (Traditional)")
 - co ("Corsican")
 - hr ("Croatian")
 - cs ("Czech")
 - da ("Danish")
 - dv ("Divehi")
 - nl ("Dutch")
 - dz ("Dzongkha")
 - en ("English")
 - eo ("Esperanto")
 - et ("Estonian")
 - ee ("Ewe")
 - fo ("Faroese")
 - fj ("Fijian")
 - fil ("Filipino")
 - fi ("Finnish")
 - fr ("French")
 - gaa ("Ga")
 - gl ("Galician")
 - lg ("Ganda")
 - ka ("Georgian")
 - de ("German")
 - el ("Greek")
 - gn ("Guarani")
 - gu ("Gujarati")
 - ht ("Haitian Creole")
 - ha ("Hausa")
 - haw ("Hawaiian")
 - iw ("Hebrew")
 - hi ("Hindi")
 - hmn ("Hmong")
 - hu ("Hungarian")
 - is ("Icelandic")
 - ig ("Igbo")
 - id ("Indonesian")
 - ga ("Irish")
 - it ("Italian")
 - ja ("Japanese")
 - jv ("Javanese")
 - kl ("Kalaallisut")
 - kn ("Kannada")
 - kk ("Kazakh")
 - kha ("Khasi")
 - km ("Khmer")
 - rw ("Kinyarwanda")
 - ko ("Korean")
 - kri ("Krio")
 - ku ("Kurdish")
 - ky ("Kyrgyz")
 - lo ("Lao")
 - la ("Latin")
 - lv ("Latvian")
 - ln ("Lingala")
 - lt ("Lithuanian")
 - luo ("Luo")
 - lb ("Luxembourgish")
 - mk ("Macedonian")
 - mg ("Malagasy")
 - ms ("Malay")
 - ml ("Malayalam")
 - mt ("Maltese")
 - gv ("Manx")
 - mi ("Māori")
 - mr ("Marathi")
 - mn ("Mongolian")
 - mfe ("Morisyen")
 - ne ("Nepali")
 - new ("Newari")
 - nso ("Northern Sotho")
 - no ("Norwegian")
 - ny ("Nyanja")
 - oc ("Occitan")
 - or ("Odia")
 - om ("Oromo")
 - os ("Ossetic")
 - pam ("Pampanga")
 - ps ("Pashto")
 - fa ("Persian")
 - pl ("Polish")
 - pt ("Portuguese")
 - pt-PT ("Portuguese (Portugal)")
 - pa ("Punjabi")
 - qu ("Quechua")
 - ro ("Romanian")
 - rn ("Rundi")
 - ru ("Russian")
 - sm ("Samoan")
 - sg ("Sango")
 - sa ("Sanskrit")
 - gd ("Scottish Gaelic")
 - sr ("Serbian")
 - crs ("Seselwa Creole French")
 - sn ("Shona")
 - sd ("Sindhi")
 - si ("Sinhala")
 - sk ("Slovak")
 - sl ("Slovenian")
 - so ("Somali")
 - st ("Southern Sotho")
 - es ("Spanish")
 - su ("Sundanese")
 - sw ("Swahili")
 - ss ("Swati")
 - sv ("Swedish")
 - tg ("Tajik")
 - ta ("Tamil")
 - tt ("Tatar")
 - te ("Telugu")
 - th ("Thai")
 - bo ("Tibetan")
 - ti ("Tigrinya")
 - to ("Tongan")
 - ts ("Tsonga")
 - tn ("Tswana")
 - tum ("Tumbuka")
 - tr ("Turkish")
 - tk ("Turkmen")
 - uk ("Ukrainian")
 - ur ("Urdu")
 - ug ("Uyghur")
 - uz ("Uzbek")
 - ve ("Venda")
 - vi ("Vietnamese")
 - war ("Waray")
 - cy ("Welsh")
 - fy ("Western Frisian")
 - wo ("Wolof")
 - xh ("Xhosa")
 - yi ("Yiddish")
 - yo ("Yoruba")
 - zu ("Zulu")

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
```

**Comment by jdepoix** [comment]
You didn't provide the language you want to your transcript to be in, so it will be english by default. You'll have to call `YouTubeTranscriptApi.get_transcript("jNzlJXQpr3k", languages=['zh-TW']))` to get the zh-TW transcript.

**Comment by doggy8088** [comment]
@jdepoix I suggest that when it cannot be found, the default response should be the first subtitle.

**Comment by jdepoix** [comment]
Thank you for the suggestion, but I disagree with this approach, as this would potentially just return transcripts in an unknown language, without the user even knowing that it is not the language which was requested.

**Comment by doggy8088** [comment]
Thanks for your reply.

I don't quite agree with this view. The reason is that the subtitles we download might be used for AI reading. AI can recognize all languages, so theoretically, any language can be understood. Therefore, providing an option to download the first subtitle in any language might be a good design.

**Comment by jdepoix** [comment]
When creating a dataset to train a model, you would quite certainly want to have control over which languages that model is trained on, therefore, this makes much more sense as a default behaviour. If you don't care about the language you can still implement your desired behaviour using the `list_transcripts` API.
