### ISSUE TITLE
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

### ISSUE THREAD

**Issue by KarenPHS** [jdepoix/youtube-transcript-api#320]
DO NOT DELETE THIS! Please take the time to fill this out properly. I am not able to help you if I do not know what you are executing and what error messages you are getting. If you are having problems with a specific video make sure to **include the video id**.

# To Reproduce

### What code / cli command are you executing?
For example: I am running
```
source = YouTubeTranscriptApi.list_transcripts("SeXZt5hqe6I")
en_caption = source.find_transcript(['en']).fetch()
```

### Which Python version are you using?
Python 3.6.4

### Which version of youtube-transcript-api are you using?
youtube-transcript-api 0.6.2

# Expected behavior
Describe what you expected to happen. 

For example: I expected to receive the english transcript

# Actual behaviour
Describe what is happening instead of the **Expected behavior**. Add **error messages** if there are any. 

For example: Instead I received the following error message:
```
  File "E:\Python Project\yt-concate-test\yt-concate\venv\lib\site-packages\youtube_transcript_api\_transcripts.py", line 293, in fetch
    _raise_http_errors(response, self.video_id).text,
  File "E:\Python Project\yt-concate-test\yt-concate\venv\lib\site-packages\youtube_transcript_api\_transcripts.py", line 358, in parse
    for xml_element in ElementTree.fromstring(plain_data)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\xml\etree\ElementTree.py", line 1315, in XML
    return parser.close()
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
```

**Comment by jdepoix** [comment]
Hi @KarenPHS, I cannot replicate that error. Does that happen for every video or only `SeXZt5hqe6I`?

**Comment by KarenPHS** [comment]
No, I tried. But it happened more than one time when I downloaded captions from videos.

`import urllib.request
from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api._errors import NoTranscriptFound, TranscriptsDisabled
from xml.etree.ElementTree import ParseError
import json

base_video_url = 'https://www.youtube.com/watch?v='
base_search_url = 'https://www.googleapis.com/youtube/v3/search?'

API_KEY=''
channel_id = 'UCKSVUHI9rbbkXhvAXK-2uxA'
first_url = base_search_url + 'key={}&channelId={}&part=snippet,id&order=date&maxResults=25'.format(API_KEY, channel_id)

video_links = []
url = first_url

# download all video links from a channel
while True:
    inp = urllib.request.urlopen(url)
    resp = json.load(inp)

    for i in resp['items']:
        if i['id']['kind'] == "youtube#video":
            video_links.append(base_video_url + i['id']['videoId'])

    try:
        next_page_token = resp['nextPageToken']
        url = first_url + '&pageToken={}'.format(next_page_token)
    except KeyError:
        break

# download all captions from all videos
for url in video_links:
    url_id = url.split('watch?v=')[-1]
    while True:
        try:
            source = YouTubeTranscriptApi.list_transcripts(url_id)
            en_caption = source.find_transcript(['en']).fetch()  # 此行已更新成 a.en，請見線上討論區至頂貼文
            break
        except (KeyError, NoTranscriptFound, TranscriptsDisabled):
            print('No captions there', url_id)
            break
        except ParseError:
            print('ParseError. there is a caption in', url, ', so, try again')
`

**Comment by jdepoix** [comment]
So it doesn't happen consistently for `SeXZt5hqe6I`, but just randomly happened once?

**Comment by Araule** [comment]
Hello, I have the same problem. For around 200 videos, I catch this error around 3-5 times every time, never the same ids.

```
Traceback (most recent call last):
  File "/home/araule/Documents/corpus/scripts/get_videos.py", line 375, in get_transcripts
    res = YouTubeTranscriptApi.get_transcript(video_id, languages=['fr'])
  File "/home/araule/miniconda3/envs/youtube/lib/python3.10/site-packages/youtube_transcript_api/_api.py", line 137, in get_transcript
    return cls.list_transcripts(video_id, proxies, cookies).find_transcript(languages).fetch(preserve_formatting=preserve_formatting)
  File "/home/araule/miniconda3/envs/youtube/lib/python3.10/site-packages/youtube_transcript_api/_transcripts.py", line 292, in fetch
    return _TranscriptParser(preserve_formatting=preserve_formatting).parse(
  File "/home/araule/miniconda3/envs/youtube/lib/python3.10/site-packages/youtube_transcript_api/_transcripts.py", line 358, in parse
    for xml_element in ElementTree.fromstring(plain_data)
  File "/home/araule/miniconda3/envs/youtube/lib/python3.10/xml/etree/ElementTree.py", line 1348, in XML
    return parser.close()
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
```
I use Python 3.10.14 and youtube-transcript-api 0.6.2 (downloaded with pip).

**Comment by KarenPHS** [comment]
> So it doesn't happen consistently for `SeXZt5hqe6I`, but just randomly happened once?

Yes, it randomly happened, but more than once.

**Comment by dgarridoa** [comment]
I got the same issue using Python 3.11.3 using youtube-transcript-api 0.6.2. And also note that happens randomly, when I retried it ended up working.

ERROR:root:no element found: line 1, column 0, 3q67v12M31M
ERROR:root:no element found: line 1, column 0, McRUxBHgFIo
ERROR:root:no element found: line 1, column 0, mokGJiXVw_4

**Comment by aketchum15** [comment]
I am also experiencing the same issue with video "sHnqCqG54Sw" along with others intermittently.
Is there any update on this issue? If there is any information on it not documented here, please let me know. I would be interested in fixing this myself if possible.

**Comment by rjhoppe** [comment]
Began experiencing this issue 2 days ago on an app that had been running flawlessly for ~3 weeks. Wonder if YouTube updated their API

**Comment by Maverick6626** [comment]
I get this same error when I start my fastapi server. Sometimes it will work without issue and on some starts it will give that error for all videos.

**Comment by Ch3my** [comment]
Im facing the same issue, here I have a trace

With this video: 9X3h3swRftY
youtube-transcript-api Version: 0.6.2 and 1.0.3 also happens

from 0.6.2 version of the plugin
```
File "youtube_transcript_api\_api.py", line 137, in get_transcript
File "youtube_transcript_api\_transcripts.py", line 292, in fetch
File "youtube_transcript_api\_transcripts.py", line 358, in parse
File "xml\etree\ElementTree.py", line 1351, in XML
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
```

The problem is that fetching the HTML in _transcripts.py fetch() the response is empty string ""; Then fails ElementTree.fromstring(raw_data)

There is a pull request, that is not merged yet, creating a custom error for this case #417. I guess a clear error is the best we can get for now.

**Comment by BobbiJ** [comment]
Same problems, all requests are falling with xml.etree.ElementTree.ParseError: no element found: line 1, column 0

**Comment by hasani114** [comment]
I'm using the youtube transcript MCP server and have started getting this error for ALL videos:

Error executing tool get_transcript: no element found: line 1, column 0

**Comment by SoulMaril** [comment]
I have the same problem. I was getting the error once or twice but now it is almost consistent and it is happening for any video I am asking for.

**Comment by jdepoix** [comment]
Hi all!

Since this issue has become increasingly prevalent during the last couple of days and most people end up commenting on #429, I will close this issue now, to keep the discussion focused to one issue!

Thank you for your input thus far! Please head over to #429 to further discus solutions! 🙂

**Comment by Senn-01** [comment]
test

**Comment by Ishara99cmyk** [comment]
have the same issue.

**Comment by jdepoix** [comment]
@Ishara99cmyk please upgrade to v1.1.0. this should resolve your issue.

**Comment by SoulMaril** [comment]
Ahh thank you. Already did and it is working well.

**Comment by Ch3my** [comment]
Thanks! issue is resolved
