### ISSUE TITLE
pip install youtube_transcript_api throws error

### ISSUE THREAD

**Issue by vijayzinnov** [jdepoix/youtube-transcript-api#5]
Collecting youtube_transcript_api
  Downloading https://files.pythonhosted.org/packages/27/92/17ce1a35de1f3cf91e206869300c63f32a8c9042c468c7b70f456acbb8af/youtube_transcript_api-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-0nDnr_/youtube-transcript-api/setup.py", line 32, in <module>
        install_requires=get_requirements(),
      File "/private/tmp/pip-install-0nDnr_/youtube-transcript-api/setup.py", line 12, in get_requirements
        return list(filter(lambda line: line != '' and not line.startswith('#'), _get_file_content('requirements.txt').split('\n')))
      File "/private/tmp/pip-install-0nDnr_/youtube-transcript-api/setup.py", line 5, in _get_file_content
        with open(file_name, 'r') as file_handler:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by jdepoix** [comment]
This error did sometimes occure on Python 2.x, but it has been fixed as of v0.1.2.
